[phases.setup]
nixPkgs = ['dotnet-sdk_9']
runtimePkgs = ['dotnet-sdk_9']

[phases.build]
cmds = [
  'dotnet restore Admin.csproj',
  'dotnet publish Admin.csproj -c Release -o out'
]

[start]
cmd = 'dotnet out/Admin.dll'
